spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  redis:
    host: ${REDIS_HOST:auth-redis}
    port: 6379

server:
  servlet:
    context-path: /uaa
  port: 5001
